- name: Deploy App on EC2
  hosts: ec2_instance
  become: true
  vars:
    docker_image: "ruslan0688/simple-js-app-jenkins"
    image_version: "app_dev_e821626"
    container_name: "simple-js-app"
    exposed_port: "81"

  tasks:
    - name: Stop and remove existing container (if running)
      shell: |
        docker ps -q --filter "name={{ container_name }}" | xargs -r docker stop
        docker ps -aq --filter "name={{ container_name }}" | xargs -r docker rm
        docker ps -q --filter "publish={{ exposed_port }}" | xargs -r docker stop
        docker ps -aq --filter "publish={{ exposed_port }}" | xargs -r docker rm
      ignore_errors: true

    - name: Free up port {{ exposed_port }} if still in use
      shell: "fuser -k {{ exposed_port }}/tcp"
      ignore_errors: true

    - name: Pull new Docker image
      shell: "docker pull {{ docker_image }}:{{ image_version }}"

    - name: Run new container
      shell: |
        docker run -d --name {{ container_name }} \
        -p 81:80 \
        {{ docker_image }}:{{ image_version }}